### ISSUE TITLE
Any way to toggle between two extensions?

### ISSUE THREAD

**Issue by johnhamm** [Meshcloud/vscode-file-ext-switcher#2]
Great extension by the way!  Was wondering if it is able to support pressing F12 once to go from a .TS file to an .HTML file, and then pressing F12 again to go from the .HTML file back to the .TS file.

**Comment by JohannesRudolph** [comment]
I have just pushed version 2.0.1 which prevents switching to the currently opened file (which also fixed another bug). It will then just keep on retrying the other available extensions bound to the command. So using the latest version, the following might work for you: 
```json
{
    "key": "F12,
    "command": "fileextswitch",
    "args": { "extensions": [".ts", ".html"] }, 
    "when": "editorTextFocus"
}
```

**Comment by JohannesRudolph** [comment]
Fixed from my point of view. Feel free to reopen.
