### ISSUE TITLE
clarify how to apply settings

### ISSUE THREAD

**Issue by bfelds** [Meshcloud/vscode-file-ext-switcher#6]
some of the language in the readme makes it seem like the "Features" section are just preferences to be set. In this extension they are all defined in the keybindings.json file. I think bringing that information up higher before the "Features" section would be more clear. 

also creating this issue for awareness for other people who run into this.

**Comment by norvegec** [comment]
Some users haven't got how to setup it and thus lowered the rating: [example](https://marketplace.visualstudio.com/items?itemName=JohannesRudolph.file-ext-switcher#review-details) which is sad, cause the extension is very handy.
Please, extend the setup manual to include it.

**Comment by JohannesRudolph** [comment]
Thanks, I'll look into this!

Dmitrii Bardakov <notifications@github.com> schrieb am Fr., 3. Aug. 2018,
17:57:

**Comment by JohannesRudolph** [comment]
Hi, I added https://github.com/Meshcloud/vscode-file-ext-switcher/commit/3b21a4707f0c05d99ebc9829bc20ffb39234e8f0 - do you think that's helpful? Happy to accept a PR to the readme to further improve upon it

**Comment by norvegec** [comment]
@JohannesRudolph ,  40e69dc . Happy to improve it. Hope it'll bring more people to use this great extension just like I do on a daily basis.
